# 应用全局配置
application:
  name: 后台作业服务
  version: 6.0.1

# 本应用的参数配置
task:
  test-key: test_value_on_local

# spring 环境配置
spring:
  main: # 支持服务名相同的Feign Client
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://10.4.208.134:3306/sei_task?characterEncoding=utf8&useSSL=false
    username: sei
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  cache:
    redis:
      time-to-live: 20s
  redis: # redis 缓存参数配置
    host: 10.4.208.132
    port: 6379
    password: ZmkDbgaua3Rso33T
    database: 0
  quartz: # quartz参数配置
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc

# sei 参数配置
sei:
  default-tenant:
    code: global
    admin: sei